core/urls.py
from django.urls import path
from core.views import index, category_list_view, product_list_view, category_product_list_view, brand_list_view, brand_product_list_view, product_detail_view
from . import views


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('products/', product_list_view, name='product-list'),
    path('product/<pid>/', product_detail_view, name='product-detail'),
    path('categories/', category_list_view, name='categories-list'),
    path('categories/<cid>/', category_product_list_view, name='category-product-list-view'),
    path('brands/', brand_list_view, name='brand-list-view'),
    path('brands/<bid>/', brand_product_list_view, name='brand-product-list-view'),
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauthentications.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from userauthentications.models import User


STATUS_CHOICE = (
    ("process", "Processing"),
    ("shipped", "Shipped"),
    ("delivered", "Delivered"),
)

STATUS = (
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("rejected", "Rejected"),
    ("in_review", "In Review"),
    ("published", "Published"),
)

RATING = (
    ( 1, "★☆☆☆☆"),
    ( 2, "★★☆☆☆"),
    ( 3, "★★★☆☆"),
    ( 4, "★★★★☆"),
    ( 5, "★★★★★"),
)

def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=20, prefix="cat", alphabet="abcdefgh12345")
    title = models.CharField(max_length=100, default="Category")
    image = models.ImageField(upload_to="category", default="categorye.jpg")

    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        return self.title
    
# class Tags(models.Model):
#     pass
    
class Brand(models.Model):
    bid = ShortUUIDField(unique=True, length=10, max_length=20, prefix="bra", alphabet="abcdef12345")
    title = models.CharField(max_length=100, default="nestify")
    image = models.ImageField(upload_to=user_directory_path, default="Brand.jpg")
    description = models.TextField(null=True, blank=True, default="Brand description")

    address = models.CharField(max_length=100, default="123 Main Street")
    contact = models.CharField(max_length=100, default="+123 (456) 789")
    chat_resp_time = models.CharField(max_length=100, default="100")
    shipping_on_time = models.CharField(max_length=100, default="100")
    authentic_rating = models.CharField(max_length=100, default="100")
    days_return = models.CharField(max_length=100, default="100")
    warranty_period = models.CharField(max_length=100, default="100")
    

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)


    class Meta:
        verbose_name_plural = "Brand"

    def brand_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        return self.title
    

class Product(models.Model):
    pid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefgh12345")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='category')
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)


    title = models.CharField(max_length=100, default="Product Title")
    image = models.ImageField(upload_to=user_directory_path, default="product.jpg")
    description = models.TextField(null=True, blank=True, default="Product description")

    price = models.DecimalField(max_digits=99999999, decimal_places=2, default=1.99)
    old_price = models.DecimalField(max_digits=99999999, decimal_places=2, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    specifications = models.TextField(null=True, blank=True)

    # tags = models.ForeignKey(Tags, on_delete=models.SET_NULL, null=True)

    product_status = models.CharField(choices=STATUS, max_length=10, default="in_review")

    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=True)
    digital = models.BooleanField(default=True)

    sku = ShortUUIDField(unique=True, length=4, max_length=10, prefix="sku", alphabet="123456790")

    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)



    class Meta:
        verbose_name_plural = "Product"

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        return self.title

    def get_percentage(self):
        new_price = (self.price / self.old_price) * 100
        return new_price
    
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product-images", default="product.jpg")
    product = models.ForeignKey(Product, related_name='p_image', on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = "ProductImages"


class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=99999999, decimal_places=2, default=1.99)
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(choices=STATUS_CHOICE, max_length=30, default="processing")

    class Meta:
        verbose_name_plural = "Cart Order"


class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    invoice_no = models.CharField(max_length=200)
    product_status = models.CharField(max_length=200)
    item = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    qty = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=99999999, decimal_places=2, default=1.99)
    total = models.DecimalField(max_digits=99999999, decimal_places=2, default=1.99)

    class Meta:
        verbose_name_plural = "Cart Order Items"

    def order_image(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))
    

class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Product Review"

    def __str__(self):
            return self.product.title
        
    def get_rating(self):
            return self.rating
        


class wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "wishlists"

        def __str__(self):
            return self.product.title
        
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=100, null=True)
    status = models.BooleanField(default=False)






 

core/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.db.models import Count

from core.models import Product, Category, Brand, CartOrder, CartOrderItems, ProductImages, ProductReview, wishlist, Address


def index(request):
    #products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status="published", featured=True).order_by("-id")

    context = {
        'products':products
    }
    return render(request, 'core/index.html', context)

def product_list_view(request):
    products = Product.objects.filter(product_status="published")

    context = {
        'products': products
    }

    return render(request, 'core/product-list.html', context)

def category_list_view(request):
    categories = Category.objects.all().annotate(product_count=Count("category"))

    context = {
        'categories': categories
    }
    return render(request, 'core/categories-list.html', context)


def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status="published", category=category)

    context = {
        'category':category,
        'products':products,
    }

    return render(request, "core/category-product-list-view.html", context)


def brand_list_view(request):
    brands = Brand.objects.all()

    context = {
        'brands': brands,
    }
    return render(request, 'core/brand-list-view.html', context)


def brand_product_list_view(request, bid):
    brand = Brand.objects.get(bid=bid)
    products = Product.objects.filter(product_status="published", brand=brand)

    context = {
        'brand':brand,
        'products':products,
    }

    return render(request, "core/brand-product-list-view.html", context)


def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    # product = get_object_or_404(product, pid=pid)

    p_image = product.p_image.all()

    context = {
        'p': product,
        'p_image': p_image,
    }


    return render(request, 'core/product-detail.html', context)

templates/core/brand-list-view.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="py-5 overflow-hidden">
    <div class="container-fluid">
      <div class="row">
         <div class="col-md-12">
           <div class="brand-carousel swiper">
             <div class="swiper-wrapper">
               {% for brand in brands %}
               <div class="swiper-slide">
                 <div class="card mb-3 p-3 rounded-4 shadow border-0">
                   <div class="row g-0">
                     <div class="col-md-4">
                       <img src="{{ brand.image.url }}" class="img-fluid rounded" alt="Card title">
                     </div>
                     <a href="{% url 'core:brand-product-list-view' brand.bid %}" class="nav-link category-item swiper-slide">
                     <div class="col-md-8">
                       <div class="card-body py-0">
                         <p class="text-muted mb-0">{{ brand.title }}</p>
                         <h5 class="card-title">{{ brand.description }}</h5>
                       </div>
                     </div>
                     </a>
                   </div>
                 </div>
               </div>
               {% endfor %}
             </div>
           </div>

         </div>
       </div>
    </div>
  </section>


{% endblock %}

templates/core/brand-product-list-view.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}


<section class="py-5 mb-5" style="background: url(assets/images/background-pattern.jpg);">
    <div class="container-fluid">
      <div class="d-flex justify-content-between">
        <h1 class="page-title pb-2">{{ brand.title }}</h1>
        <nav class="breadcrumb fs-6">
          <a class="breadcrumb-item nav-link" href="#">Home</a>
          <a class="breadcrumb-item nav-link" href="#">Pages</a>
          <span class="breadcrumb-item active" aria-current="page">Shop</span>
        </nav>
      </div>
    </div>
  </section>
<section class="main-container col2-left-layout">
    <div class="container">
        <p>Total {{ products.count }} product{{ products.count|pluralize}}</p>
        <div class="row">
            <div class="product-grid row row-cols-sm-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4">
                {% for p in products %}
                <div class="col">
                  <div class="product-item">
                    <span class="badge bg-success position-absolute m-3">-30%</span>
                    <a href="#" class="btn-wishlist"><svg width="24" height="24"><use xlink:href="#heart"></use></svg></a>
                    <figure>
                      <a href="single-product.html" title="Product Title">
                        <img src="{{ p.image.url }}" alt="Product Thumbnail" class="tab-image">
                      </a>
                    </figure>
                    <h3>{{ p.title }}</h3>
                    <span class="qty">1 Unit</span><span class="rating"><svg width="24" height="24" class="text-primary"><use xlink:href="#star-solid"></use></svg> 4.5</span>
                    <span class="price">${{ p.price }}</span>
                    <div class="d-flex align-items-center justify-content-between">
                      <div class="input-group product-qty">
                          <span class="input-group-btn">
                              <button type="button" class="quantity-left-minus btn btn-danger btn-number" data-type="minus">
                                <svg width="16" height="16"><use xlink:href="#minus"></use></svg>
                              </button>
                          </span>
                          <input type="text" name="quantity" class="form-control input-number quantity" value="1">
                          <span class="input-group-btn">
                              <button type="button" class="quantity-right-plus btn btn-success btn-number" data-type="plus">
                                  <svg width="16" height="16"><use xlink:href="#plus"></use></svg>
                              </button>
                          </span>
                      </div>
                      <a href="#" class="nav-link">Add to Cart <svg width="18" height="18"><use xlink:href="#cart"></use></svg></a>
                    </div>
                  </div>
                </div>
                {% endfor %}
            </div>
              <!-- / product-grid -->

        </div>
    </div>
</section>



{% endblock content %}

templates/core/categories-list.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="py-5 overflow-hidden">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="section-header d-flex flex-wrap justify-content-between mb-5">
            <h2 class="section-title">Category</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="category-carousel swiper">
            <div class="swiper-wrapper">
            {% for c in categories %}
              <a href="{% url 'core:category-product-list-view' c.cid %}" class="nav-link category-item swiper-slide">
                <img src="{{ c.image.url }}" alt="Category Thumbnail">
                <h3 class="category-title">{{ c.title }}</h3>
                <p>Total {{ c.category.count }} Product{{ c.category.count|pluralize}}</p>
              </a>
            {% endfor %}                  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


{% endblock %}

templates/core/categories-list1.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}



<div class="featured-pro-block">
    <div class="slider-items-products">
        <div class="new-arrivals-block">
            <div class="block-title">
                <h2>Categories</h2>
            </div>
            <div id="new-arrivals-slider" class="product-flexslider hidden-buttons">
                <div class="home-block-inner"> </div>
                <div class="slider-items slider-width-col4 products-grid block-content">
                {% for c in categories %}
                    <div class="item">
                        <div class="item-inner">
                            <div class="item-img">
                                <div class="item-img-info"> <a class="product-image" title="Retis lapen casen" href="product_detail.html"> <img alt="Retis lapen casen" src="{{ c.image.url }}"> </a>
                                </div>
                            </div>
                            <div class="item-info">
                                <div class="info-inner">
                                    <div class="item-title"> <a title="Retis lapen casen" href="{% url 'core:category-product-list-view' c.cid %}"> {{ c.title }} </a> </div>
                                    <div class="item-content">
                                        <div class="item-price">
                                            <div class="price-box">
                                                <span class="price">{{ c.category.count }} Product{{ c.category.count|pluralize }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End Item -->
                {% endfor %}
                </div>
                <div>
                    <ul>
                        {% for c in categories %}
                        <li>{{ c.title }} <span>{{ c.category.count }}</span></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/core/category-product-list-view.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}


<section class="main-container col2-left-layout">
    <div class="container">
        <div class="row">
            <div class="col-md-9 col-sm-8 col-xs-12 col-sm-push-4 col-md-push-3">
                <!-- bestsell slider -->
                <div class="bestsell-pro">
                    <div>
                        <div class="slider-items-products">
                            <div class="bestsell-block">
                                <div class="block-title">
                                    <h2>{{ category.title }}</h2> <p>{{ products.count }} product{{ products.count|pluralize}}</p>
                                </div>
                                <p>Home > Shop > {{ category.title }}</p>
                                <div id="bestsell-slider" class="product-flexslider hidden-buttons">
                                    <div class="slider-items slider-width-col4 products-grid block-content">
                                        {% for p in products %}
                                        <div class="item">
                                            <div class="item-inner">
                                                <div class="item-img">
                                                    <div class="item-img-info"> <a class="product-image" title="Retis lapen casen" href="product_detail.html"> <img alt="Retis lapen casen" src="{{ p.image.url }}"> </a>
                                                        <div class="new-label new-top-right">new</div>
                                                        <div class="box-hover">
                                                            <ul class="add-to-links">
                                                                <li><a class="link-quickview" href="quick_view.html"></a></li>
                                                                <li><a class="link-wishlist" href="wishlist.html"></a></li>
                                                                <li><a class="link-compare" href="compare.html"></a></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="item-info">
                                                    <div class="info-inner">
                                                        <div class="item-title"> <a title="Retis lapen casen" href="product_detail.html"> {{ p.title }} </a> </div>
                                                        <div class="rating">
                                                            <div class="ratings">
                                                                <div class="rating-box">
                                                                    <div class="rating width80"></div>
                                                                </div>
                                                                <p class="rating-links"> <a href="#">1 Review(s)</a> <span class="separator">|</span> <a href="#">Add Review</a> </p>
                                                            </div>
                                                        </div>
                                                        <div class="item-content">
                                                            <div class="item-price">
                                                                <div class="price-box"> 
                                                                    <span class="regular-price">{{ p.old_price }}</span>
                                                                    <span class="price">{{ p.price }}</span>
                                                                </div>
                                                            </div>
                                                            <div class="action">
                                                                <button class="button btn-cart" type="button" title="" data-original-title="Add to Cart"><span>Add to Cart</span> </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}

                                        <!-- Item -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



{% endblock content %}

templates/core/category-product-list-view1.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}


<section class="main-container col2-left-layout">
    <div class="container">
        <div class="row">
            <div class="col-md-9 col-sm-8 col-xs-12 col-sm-push-4 col-md-push-3">
                <!-- bestsell slider -->
                <div class="bestsell-pro">
                    <div>
                        <div class="slider-items-products">
                            <div class="bestsell-block">
                                <div class="block-title">
                                    <h2>{{ category.title }}</h2> <p>{{ products.count }} product{{ products.count|pluralize}}</p>
                                </div>
                                <p>Home > Shop > {{ category.title }}</p>
                                <div id="bestsell-slider" class="product-flexslider hidden-buttons">
                                    <div class="slider-items slider-width-col4 products-grid block-content">
                                        {% for p in products %}
                                        <div class="item">
                                            <div class="item-inner">
                                                <div class="item-img">
                                                    <div class="item-img-info"> <a class="product-image" title="Retis lapen casen" href="product_detail.html"> <img alt="Retis lapen casen" src="{{ p.image.url }}"> </a>
                                                        <div class="new-label new-top-right">new</div>
                                                        <div class="box-hover">
                                                            <ul class="add-to-links">
                                                                <li><a class="link-quickview" href="quick_view.html"></a></li>
                                                                <li><a class="link-wishlist" href="wishlist.html"></a></li>
                                                                <li><a class="link-compare" href="compare.html"></a></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="item-info">
                                                    <div class="info-inner">
                                                        <div class="item-title"> <a title="Retis lapen casen" href="product_detail.html"> {{ p.title }} </a> </div>
                                                        <div class="rating">
                                                            <div class="ratings">
                                                                <div class="rating-box">
                                                                    <div class="rating width80"></div>
                                                                </div>
                                                                <p class="rating-links"> <a href="#">1 Review(s)</a> <span class="separator">|</span> <a href="#">Add Review</a> </p>
                                                            </div>
                                                        </div>
                                                        <div class="item-content">
                                                            <div class="item-price">
                                                                <div class="price-box"> 
                                                                    <span class="regular-price">{{ p.old_price }}</span>
                                                                    <span class="price">{{ p.price }}</span>
                                                                </div>
                                                            </div>
                                                            <div class="action">
                                                                <button class="button btn-cart" type="button" title="" data-original-title="Add to Cart"><span>Add to Cart</span> </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}

                                        <!-- Item -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



{% endblock content %}