core/urls.py
from django.urls import path
from core.views import index, category_list_view, product_list_view, category_product_list_view, brand_list_view, brand_product_list_view, product_detail_view
from . import views


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('products/', product_list_view, name='product-list'),
    path('product/<pid>/', product_detail_view, name='product-detail'),
    path('categories/', category_list_view, name='categories-list'),
    path('categories/<cid>/', category_product_list_view, name='category-product-list-view'),
    path('brands/', brand_list_view, name='brand-list-view'),
    path('brands/<bid>/', brand_product_list_view, name='brand-product-list-view'),
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauthentications.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauthentications/urls.py
from django.urls import path
from userauthentications import views

app_name = "userauthentications"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out")
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


    def __str__(self):
        return self.username

templates/userauths/sign-in.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
<section class="py-5 mb-5" style="background: url(images/background-pattern.jpg);">
    <!-- <div class="container-fluid">
      <div class="d-flex justify-content-between">
        <h1 class="page-title pb-2">Login</h1>
        <nav class="breadcrumb fs-6">
          <a class="breadcrumb-item nav-link" href="#">Home</a>
          <a class="breadcrumb-item nav-link" href="#">Pages</a>
          <span class="breadcrumb-item active" aria-current="page">Checkout</span>
        </nav>
      </div>
    </div> -->
    <div class="container-sm">
      <div class="row justify-content-center">
        <div class="col-lg-4 p-5 bg-white border shadow-sm">
          <h5 class="text-uppercase mb-4">Login</h5>
          <form method="POST">
            {% csrf_token %}
            <div class="col-12 pb-3">
              <label class="d-none">Email address *</label>
              <input type="text" name="email" placeholder="email" class="form-control" required>
            </div>
            <div class="col-12 pb-3">
              <label class="d-none">Password *</label>
              <input type="password" name="password" placeholder="Password" class="form-control" required>
            </div>
            <!-- <div class="col-12 pb-3">
              <label>
                <input type="checkbox" required="">
                <span class="label-body">Remember me</span>
              </label>
            </div> -->
            <div class="col-12">
              <button type="submit" name="submit" class="btn btn-primary text-uppercase w-100">Log in</button>
              <p><a href="{% url 'userauthentications:sign-up' %}">Don't have an account? You can register.</a></p>
            </div>
          </form>
        </div>
      </div>
    </div>
</section>
{% endblock content %}

templates/userauths/sign-in1.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <form class="login100-form validate-form">
                <span class="login100-form-title p-b-26">
                    Login
                </span>
                <span class="login100-form-title p-b-48">
                    <i class="zmdi zmdi-font"></i>
                </span>

                <div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
                    <input class="input100" type="text" name="email" required>
                    <span class="focus-input100" data-placeholder="Email"></span>
                </div>

                <div class="wrap-input100 validate-input" data-validate="Enter password">
                    <span class="btn-show-pass">
                        <i class="zmdi zmdi-eye"></i>
                    </span>
                    <input class="input100" type="password" name="pass" required>
                    <span class="focus-input100" data-placeholder="Password"></span>
                </div>

                <div class="container-login100-form-btn">
                    <div class="wrap-login100-form-btn">
                        <div class="login100-form-bgbtn"></div>
                        <button class="login100-form-btn">
                            Login
                        </button>
                    </div>
                </div>

                <div class="text-center p-t-115">
                    <span class="txt1">
                        Dont have an account?
                    </span>

                    <a class="txt2" href="{% url 'userauthentications:sign-up' %}">
                        Sign Up
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userauths/sign-up.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<section class="py-5 mb-5" style="background: url(images/background-pattern.jpg);">
    <!-- <div class="container-fluid">
      <div class="d-flex justify-content-between">
        <h1 class="page-title pb-2">Registration</h1>
        <nav class="breadcrumb fs-6">
          <a class="breadcrumb-item nav-link" href="#">Home</a>
          <a class="breadcrumb-item nav-link" href="#">Pages</a>
          <span class="breadcrumb-item active" aria-current="page">Checkout</span>
        </nav>
      </div>
    </div> -->
    <div class="container-sm">
      <div class="row justify-content-center">
        <div class="col-lg-4 p-5 bg-white border shadow-sm">
          <h5 class="text-uppercase mb-4">Sign Up</h5>
          {% if form.errors %}
          <div class="alert alert-danger">
            error
            {{ form.errors }}
          </div>
          {% endif %}
          <form id="form" class="form-group flex-wrap" method="post" method="POST">
            {% csrf_token %}
            <div class="col-12 pb-3">
              {{ form.username }}
            </div>
            <div class="col-12 pb-3">
              {{ form.email }}
            </div>
            <div class="col-12 pb-3">
              {{ form.password1 }}
            </div>
            <div class="col-12 pb-3">
              {{ form.password2 }}
            </div>

            <!-- <div class="col-12 pb-3">
              <label>
                <input type="checkbox" required="">
                <span class="label-body">Remember me</span>
              </label>
            </div> -->
            <div class="col-12">
              <button type="submit" name="submit" class="btn btn-primary text-uppercase w-100">Create Account</button>
              <p><a href="{% url 'userauthentications:sign-in' %}">Don have an account? Login here.</a></p>
            </div>
          </form>
        </div>
      </div>
    </div>
</section>

<!-- <form method="post" method="POST">
    {% csrf_token %}

    {{form.username}}
    {{form.email}}
    {{form.password1}}
    {{form.password2}}
    
    <button type="submit">Submit</button>
</form> -->

{% endblock content %}

templates/userauths/sign-up1.html
{% if form.errors %}
    <strong>Errror</strong>
{% endif %}


<form method="post" method="POST">
    {% csrf_token %}

    {{form.username}}
    {{form.email}}
    {{form.password1}}
    {{form.password2}}
    
    <button type="submit">Submit</button>
</form>
<p>you can <a href="{% url 'userauthentications:sign-in' %}">login</a></p>